/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcInicioParida;

import java.awt.Color;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author juanpheras
 */
public class VistaRegistrarJugador extends javax.swing.JFrame implements ISuscriptor {

    private String linkAvatarSeleccionado;

    private String nombreJugador;

    private ControlInicioPartida control;

    Map<Integer, Color> mapaColores;

    /**
     * Creates new form VistaRegistrarJugador
     */
    public VistaRegistrarJugador(ControlInicioPartida control) {
        initComponents();
        cargarAvatares();
        this.setLocationRelativeTo(null);
        this.control = control;
        configurarSeleccionColor(pnlColorA);
        configurarSeleccionColor(pnlColorB);
        configurarSeleccionColor(pnlColorC);
        configurarSeleccionColor(pnlColorD);
        this.txtNombre.setText(nombreJugador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlColorA = new javax.swing.JPanel();
        pnlColorB = new javax.swing.JPanel();
        pnlColorC = new javax.swing.JPanel();
        pnlColorD = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        lblAvatar1 = new javax.swing.JLabel();
        lblAvatar2 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();
        lblAvatar4 = new javax.swing.JLabel();
        lblAvatar5 = new javax.swing.JLabel();
        lblAvatar6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 152, 198));

        jPanel1.setBackground(new java.awt.Color(30, 152, 198));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Storyboard Rummy V1 - Equipo 01.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 232, 151));

        lblAvatar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAvatar.setText("Avatar:");

        txtNombre.setEnabled(false);

        lblNombre.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblNombre.setText("Nombre:");
        lblNombre.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("Colores de fichas:");

        pnlColorA.setBackground(new java.awt.Color(255, 0, 0));
        pnlColorA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlColorALayout = new javax.swing.GroupLayout(pnlColorA);
        pnlColorA.setLayout(pnlColorALayout);
        pnlColorALayout.setHorizontalGroup(
            pnlColorALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlColorALayout.setVerticalGroup(
            pnlColorALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlColorB.setBackground(new java.awt.Color(51, 51, 255));
        pnlColorB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlColorBLayout = new javax.swing.GroupLayout(pnlColorB);
        pnlColorB.setLayout(pnlColorBLayout);
        pnlColorBLayout.setHorizontalGroup(
            pnlColorBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlColorBLayout.setVerticalGroup(
            pnlColorBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlColorC.setBackground(new java.awt.Color(51, 255, 51));
        pnlColorC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlColorCLayout = new javax.swing.GroupLayout(pnlColorC);
        pnlColorC.setLayout(pnlColorCLayout);
        pnlColorCLayout.setHorizontalGroup(
            pnlColorCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlColorCLayout.setVerticalGroup(
            pnlColorCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlColorD.setBackground(new java.awt.Color(0, 0, 0));
        pnlColorD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlColorDLayout = new javax.swing.GroupLayout(pnlColorD);
        pnlColorD.setLayout(pnlColorDLayout);
        pnlColorDLayout.setHorizontalGroup(
            pnlColorDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlColorDLayout.setVerticalGroup(
            pnlColorDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        btnContinuar.setBackground(new java.awt.Color(102, 153, 255));
        btnContinuar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblAvatar1.setMaximumSize(new java.awt.Dimension(35, 35));
        lblAvatar1.setMinimumSize(new java.awt.Dimension(35, 35));
        lblAvatar1.setPreferredSize(new java.awt.Dimension(35, 35));

        lblAvatar2.setMaximumSize(new java.awt.Dimension(35, 35));
        lblAvatar2.setMinimumSize(new java.awt.Dimension(35, 35));
        lblAvatar2.setPreferredSize(new java.awt.Dimension(35, 35));

        lblAvatar3.setMaximumSize(new java.awt.Dimension(35, 35));
        lblAvatar3.setMinimumSize(new java.awt.Dimension(35, 35));
        lblAvatar3.setPreferredSize(new java.awt.Dimension(35, 35));

        lblAvatar4.setMaximumSize(new java.awt.Dimension(35, 35));
        lblAvatar4.setMinimumSize(new java.awt.Dimension(35, 35));
        lblAvatar4.setPreferredSize(new java.awt.Dimension(35, 35));

        lblAvatar5.setMaximumSize(new java.awt.Dimension(35, 35));
        lblAvatar5.setMinimumSize(new java.awt.Dimension(35, 35));
        lblAvatar5.setPreferredSize(new java.awt.Dimension(35, 35));

        lblAvatar6.setMaximumSize(new java.awt.Dimension(35, 35));
        lblAvatar6.setMinimumSize(new java.awt.Dimension(35, 35));
        lblAvatar6.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pnlColorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlColorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlColorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlColorD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblAvatar)
                                .addGap(18, 18, 18)
                                .addComponent(lblAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAvatar5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAvatar6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAvatar5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvatar6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColorA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlColorB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlColorC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlColorD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        if (validarInputsAvatarUser()) {
//            JOptionPane.showMessageDialog(this, "Registrado");
            control.enviarRegistro(linkAvatarSeleccionado, obtenerMapaColores());
        } else {
            JOptionPane.showMessageDialog(this, "Por favor selecicona un avatar e ingresa un nombre.");
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private Map<Integer, Color> obtenerMapaColores() {

        Map<Integer, Color> mapa = new HashMap<>();

        mapa.put(1, pnlColorA.getBackground());
        mapa.put(2, pnlColorB.getBackground());
        mapa.put(3, pnlColorC.getBackground());
        mapa.put(4, pnlColorD.getBackground());

        return mapa;
    }

    private boolean validarInputsAvatarUser() {
        return linkAvatarSeleccionado != null
                && !linkAvatarSeleccionado.trim().isEmpty();
    }

    private ImageIcon cargarYEscalar(String ruta, int width, int height) {
        ImageIcon icon = new ImageIcon(getClass().getResource(ruta));
        Image img = icon.getImage();
        Image scaled = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);
    }

    private void configurarAvatar(JLabel label, String ruta) {
        label.setIcon(cargarYEscalar(ruta, 50, 50));

        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                linkAvatarSeleccionado = ruta;
                resaltarAvatar(label);
                System.out.println("Avatar seleccionado: " + linkAvatarSeleccionado);
            }
        });
    }

    private void resaltarAvatar(JLabel seleccionado) {
        // Limpia bordes de todos
        JLabel[] labels = {lblAvatar1, lblAvatar2, lblAvatar3, lblAvatar4, lblAvatar5, lblAvatar6};
        for (JLabel lbl : labels) {
            lbl.setBorder(null);
        }

        // Aplica borde al icnonoseleccionado
        seleccionado.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.YELLOW, 3));
    }

    private void cargarAvatares() {
        configurarAvatar(lblAvatar1, "/imgs/avatar1.png");
        configurarAvatar(lblAvatar2, "/imgs/avatar2.png");
        configurarAvatar(lblAvatar3, "/imgs/avatar3.png");
        configurarAvatar(lblAvatar4, "/imgs/avatar4.png");
        configurarAvatar(lblAvatar5, "/imgs/avatar5.png");
        configurarAvatar(lblAvatar6, "/imgs/avatar6.jpg");
    }

    private boolean colorYaUsado(Color color, JPanel panelActual) {
        JPanel[] panels = {pnlColorA, pnlColorB, pnlColorC, pnlColorD};

        for (JPanel p : panels) {
            if (p != panelActual && p.getBackground().equals(color)) {
                return true;
            }
        }
        return false;
    }

    private void configurarSeleccionColor(javax.swing.JPanel panel) {
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                Color nuevoColor = javax.swing.JColorChooser.showDialog(
                        VistaRegistrarJugador.this,
                        "Selecciona un color",
                        panel.getBackground()
                );

                if (nuevoColor != null) {
                    // Validamos si ya está en uso
                    if (colorYaUsado(nuevoColor, panel)) {
                        JOptionPane.showMessageDialog(
                                VistaRegistrarJugador.this,
                                "Ese color ya está seleccionado en tu lista.\nElige uno distinto.",
                                "Color repetido",
                                JOptionPane.WARNING_MESSAGE
                        );
                        return; // NO aplicar el color
                    }
                    panel.setBackground(nuevoColor);
                    panel.repaint();
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JLabel lblAvatar5;
    private javax.swing.JLabel lblAvatar6;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlColorA;
    private javax.swing.JPanel pnlColorB;
    private javax.swing.JPanel pnlColorC;
    private javax.swing.JPanel pnlColorD;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(IModeloInicioPartida modelo) {
        if (modelo.isJugadorRegistrado()) {
            this.dispose();
            //CONTROL.INICIARTABLERO(MAPACOLORES, NOMBREJUGADOR)
        } else {
            JOptionPane.showMessageDialog(this, modelo.obtenerMensaje());
        }
    }
}
